name: build-controller

on:
    workflow_call: 
        inputs:
            changed_files:
                required: true
                description: 'Provides details of files changed'
                type: string
            pr_build_version:
                required: true
                description: 'Provides versioning details of the PR'
                type: string
            linux_platform_build:
                required: true
                description: "Flag for linux platform build"
                type: boolean
            windows_platform_build:
                required: true
                description: "Flag for windows platform build"
                type: boolean

jobs:
    build-cpp-linux:
        if: ${{ inputs.changed_files == 'CPP' && inputs.linux_platform_build }}
        uses: ./.github/workflows/build-cpp-linux.yml
        secrets: inherit
        with:
            pr_build_version: ${{ inputs.pr_build_version }}

    build-cpp-windows:
        if: ${{ inputs.changed_files == 'CPP' && inputs.windows_platform_build }}
        uses: ./.github/workflows/build-cpp-windows.yml
        secrets: inherit
        with:
            pr_build_version: ${{ inputs.pr_build_version }}