name: build-controller

on:
    workflow_call:
        inputs:
            version_tag:
                description: "Provides the version tag for the workflow run"
                required: true
                type: string

            build_file_type:
                description: "Provides the information about the file type to be built"
                required: true
                type: string

            target_linux_platform:
                description: "Flag to enable build targeting the linux platform"
                required: true
                type: boolean

            target_windows_platform:
                description: "Flag to enable build targeting the windows platform"
                required: true
                type: boolean
                

jobs:
    build-cpp:
        uses: ./.github/workflows/build-cpp.yml
        if: ${{ inputs.build_file_type == 'CPP' }}
        secrets: inherit
        with:
            target_linux_platform: ${{ inputs.target_linux_platform }}
            target_windows_platform: ${{ inputs.target_windows_platform }}
            version_tag: ${{ inputs.version_tag }}


    build-docker:
        uses: ./.github/workflows/build-docker.yml
        if: ${{ inputs.build_file_type == 'DOCKER' }}
        secrets: inherit
        with:
            target_linux_platform: ${{ inputs.target_linux_platform }}
            target_windows_platform: ${{ inputs.target_windows_platform }}
            version_tag: ${{ inputs.version_tag }}
