# The CPP workflows expect the CPP projects to have CMake configurations
# The configurations are supposed to contain definitions for the CMake configure and build presets at the least
# This is to allow the modularity in the workflows
# If the tests are supposed to be run please do have a testing preset configured as well.

name: build-trigger-cpp

on:
    workflow_call: 
        inputs:
            pr_build_version:
                required: true
                description: 'Provides versioning details of the PR'
                type: string
            linux_platform_build:
                required: true
                description: "Flag for linux platform build"
                type: boolean
            windows_platform_build:
                required: true
                description: "Flag for windows platform build"
                type: boolean

jobs:
    cpp-build-linux:
        if: ${{ inputs.linux_platform_build }}
        uses: ./.github/workflows/build-workflows/cpp/build-cpp-linux.yml
        secrets: inherit
        with:
            pr_build_version: ${{ inputs.pr_build_version }}

    cpp-build-windows:
        if: ${{ inputs.windows_platform_build }}
        uses: ./.github/workflows/build-workflows/cpp/build-cpp-windows.yml
        secrets: inherit
        with:
            pr_build_version: ${{ inputs.pr_build_version }}
        