name: build-controller.yml

on:
    workflow_call: 
        inputs:
            changed_files:
                required: true
                description: 'Provides details of files changed'
                type: string
            pr_build_version:
                required: true
                description: 'Provides versioning details of the PR'
                type: string
            linux_platform_build:
                required: true
                description: "Flag for linux platform build"
                type: boolean
            windows_platform_build:
                required: true
                description: "Flag for windows platform build"
                type: boolean

jobs:
    trigger-build-cpp:
        if: ${{ inputs.changed_files == 'CPP' }}
        uses: ./.github/workflows/build-trigger-cpp.yml
        secrets: inherit
        with:
            pr_build_version: ${{ inputs.pr_build_version }}
            linux_platform_build: ${{ inputs.linux_platform_build }}
            windows_platform_build: ${{ inputs.windows_platform_build }}