name: PR-Workflow-Template

on:
    workflow_call: 
        inputs:
            workflow_type:
                required: true
                description: "Defines the workflow type i.e. PR/CI"
                type: string

concurrency: 
    group:  ${{ github.head_ref }}-${{ github.base_ref }}
    cancel-in-progress: true

jobs:
    ci-versioning:
        uses: ./.github/workflows/versioning.yml
        secrets: inherit
        with:
            trigger_type: ${{ inputs.workflow_type }}