name: PR-Workflow-Template

on:
    workflow_call: 
        inputs:
            workflow_type:
                required: true
                description: "Defines the workflow type i.e. PR/CI"
                type: string
            changed_files:
                required: true
                description: "Describes the files changed in the PR/CI"
                type: string
            linux_platform_build:
                required: true
                description: "Flag for linux platform build"
                type: boolean
            windows_platform_build:
                required: true
                description: "Flag for windows platform build"
                type: boolean

concurrency: 
    group:  ${{ github.head_ref }}-${{ github.base_ref }}
    cancel-in-progress: true

jobs:
    ci-versioning:
        uses: ./.github/workflows/versioning.yml
        secrets: inherit
        with:
            trigger_type: ${{ inputs.workflow_type }}