name: pr-workflow

on:
    workflow_call: 
        inputs:
            workflow_type:
                description: "Describes the workflow type"
                required: true
                type: string

            build_file_type:
                description: "Provides the information about the file type to be built"
                required: true
                type: string

            target_linux_platform:
                description: "Flag to enable build targeting the linux platform"
                required: true
                type: boolean

            target_windows_platform:
                description: "Flag to enable build targeting the windows platform"
                required: true
                type: boolean

jobs:
    versioning:
        uses: ./.github/workflows/versioning.yml
        secrets: inherit
        with:
            workflow_type: ${{ inputs.workflow_type }}

    build-cpp-target:
        needs: versioning
        if: ${{ inputs.build_file_type == 'CPP' && !contains(needs.versioning.outputs.version_tag, 'doc') }}
        uses: ./.github/workflows/build-cpp.yml
        secrets: inherit
        with:
            version_tag: ${{ needs.versioning.outputs.version_tag }}
            target_linux_platform: ${{ inputs.target_linux_platform }}
            target_windows_platform: ${{ inputs.target_windows_platform }}
