name: versioning

on:
    workflow_call: 
        inputs:
            trigger_type:
                required: true
                description: "Defines the type of versioning trigger i.e. (PR or CI)"
                type: string

        outputs:
            version_info:
                value: ${{ jobs.pr-versioning.outputs.pr-build-tag || jobs.ci-versioning.outputs.ci-version-tag }}
                description: "Appropriate version tag for PR or CI"
    
jobs:
    pr-versioning:
        timeout-minutes: 10
        runs-on: [ ubuntu-latest ]
        if: ${{ inputs.trigger_type == 'PR' }}

        outputs:
            pr-build-tag: ${{ steps.generate-pr-tag.outputs.PR_BUILD_TAG }}

        steps:
            - name: Checkout Branch
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
                token: ${{ secrets.GITHUB_TOKEN }}

            - name: Generate PR build tag
              id: generate-pr-tag
              run: |
                shortened_sha=$(echo "${{ github.sha }} | cut -c 1-7")
                echo "PR_BUILD_TAG=BUILD_$shortened_sha" >> $GITHUB_OUTPUT

    ci-versioning:
        timeout-minutes: 10
        runs-on: [ ubuntu-latest ]
        if: ${{ inputs.trigger_type == 'CI' }}

        outputs:
            ci-version-tag: ${{ steps.generate-ci-tag.outputs.CI_BUILD_TAG }}

        steps:
          - name: Checkout Branch
            uses: actions/checkout@v4
            with:
              fetch-depth: 0
              token: ${{ secrets.GITHUB_TOKEN }}

          - name: Generate CI tag
            id: generate-ci-tag
            run: |
              echo "CI_BUILD_TAG=$(git log --merges --oneline ${{ github.base_ref }} | wc -l)"
