name: versioning

on:
    pull_request: 
        branches: master
        types: [ opened, synchronize, reopened ]
    # workflow_call: 
    #     inputs:
    #         workflow_type:
    #             description: Describes the workflow type
    #             required: true
    #             type: string

jobs:
    versioning:
        runs-on: [ ubuntu-latest ]
        timeout-minutes: 15
        
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Get change context
              id: path-filter
              uses: dorny/paths-filter@v3
              with:
                list-files: csv
                filters: .github/filters.yml
