name: versioning

on:
    workflow_call: 
        inputs:
            workflow_type:
                description: "Describes the workflow type"
                required: true
                type: string

        outputs:
            version_tag:
                description: "Gives the complete version tag for the workflow run"
                value: ${{ jobs.complete-tag-creation.outputs.version_tag }}

jobs:
    tagging-change-context:
        uses: ./.github/workflows/tagging_change_context.yml
        secrets: inherit

    tagging-workflow-type:
        uses: ./.github/workflows/tagging_workflow_type.yml
        secrets: inherit
        with:
            workflow_type: ${{ inputs.workflow_type }}

    complete-tag-creation:
        needs: [ tagging-change-context, tagging-workflow-type ]
        runs-on: [ ubuntu-latest ]
        timeout-minutes: 10

        outputs:
            version_tag: ${{ steps.complete-workflow-tag.outputs.version_tag }}
        
        steps:
            - name: Generate complete version tag for workflow
              id: complete-workflow-tag
              run: |
                echo "version_tag=${{ needs.tagging-workflow-type.outputs.workflow_type_tag }}_${{ needs.tagging-change-context.outputs.change_context_tag }}" >> $GITHUB_OUTPUT