name: versioning

on:
    pull_request: 
        branches: master
        types: [ opened, synchronize, reopened ]
    # workflow_call: 
    #     inputs:
    #         workflow_type:
    #             description: Describes the workflow type
    #             required: true
    #             type: string

jobs:
    versioning:
        runs-on: [ ubuntu-latest ]
        timeout-minutes: 15
        
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Get change context
              id: path-filter
              uses: dorny/paths-filter@v3
              with:
                list-files: csv
                filters: .github/filters.yml

            - name: Show outputs
              run: |
                echo ${{ steps.path-filter.outputs.code_filters }}
                echo ${{ steps.path-filter.outputs.environment_filters }}
                echo ${{ steps.path-filter.outputs.workflow_filters }}
                echo ${{ steps.path-filter.outputs.unit_test_filters }}
                echo ${{ steps.path-filter.outputs.doc_filters }}

            - name: Tag run for codebase change
              if: ${{ steps.path-filter.outputs.code_filters == 'true' }}
              id: code-update-tag
              run:
                echo "change_context_tag=build" >> $GITHUB_OUTPUT

            - name: Tag run for build environment change
              if: ${{ steps.path-filter.outputs.code_filters == 'false' && steps.path-filter.outputs.environment_filters == 'true' }}
              id: environment-update-tag
              run:
                echo "change_context_tag=env" >> $GITHUB_OUTPUT

            - name: Tag run for workflow change
              if: ${{ !steps.path-filter.outputs.environment_filters == 'false' && steps.path-filter.outputs.workflow_filters == 'true' }}
              id: workflow-update-tag
              run: 
                echo "change_context_tag=wflow" >> $GITHUB_OUTPUT

            - name: Tag run for unit test change
              if: ${{ !steps.path-filter.outputs.workflow_filters == 'false' && steps.path-filter.outputs.unit_test_filters == 'true' }}
              id: unit-test-update-tag
              run:
                echo "change_context_tag=test" >> $GITHUB_OUTPUT

            - name: Tag run for document change
              if: ${{ !steps.path-filter.outputs.unit_test_filters == 'false' && steps.path-filter.outputs.doc_filters == 'true' }}
              id: doc-update-tag
              run:
                echo "change_context_tag=doc" >> $GITHUB_OUTPUT
